### ISSUE TITLE
Updated nuget package

### ISSUE THREAD

**Issue by sbruyere** [rossknudsen/Kavod.Vba.Compression#4]
Hello Ross !
Do you have a possibility to update the nuget package so that it take in account the last changes ? :)

Thanks !

**Comment by rossknudsen** [comment]
Hi @sbruyere ,

Sure, no problem.  I have just updated now, it may take a couple of hours before it becomes generally available.  See here:  https://www.nuget.org/packages/Kavod.Vba.Compression/0.0.2-alpha

I also am playing around with Azure DevOps at the moment - so you'll see a branch with some work in it.  I've got it building OK, but need to work on the continuous deployment part.

**Comment by sbruyere** [comment]
Thanks Ross ! Wonderful job  :)

Le lun. 29 avr. 2019 à 12:12, Ross Knudsen <notifications@github.com> a
écrit :
